name: Update repo with new Firefox nightly release info.

on:
  schedule:
  - cron: "55 * * * *"

jobs:
  auto-update:

    runs-on: ubuntu-latest
    env:
      git_user_name: github-actions
      git_user_mail: github-actions@github.com
    steps:
    - uses: actions/checkout@v3
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
        repository: calbrecht/f4s-firefox-nightly
        ref: main
    - uses: cachix/install-nix-action@v18
      with:
        install_url: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.13.0pre20221223_14f7dae/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix run .github#auto-update
