name: Update repo with new Firefox nightly release info.

on:
  schedule:
  - cron: "55 * * * *"

jobs:
  auto-update:

    runs-on: ubuntu-latest
    env:
      git_user_name: github-actions
      git_user_mail: github-actions@github.com
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-tags: true
    - uses: cachix/install-nix-action@v31
    - run: nix run .github#auto-update
